<?php

/**
 * @file
 * Contains prjo_dap.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function prjo_dap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the prjo_dap module.
    case 'help.page.prjo_dap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function prjo_dap_theme() {
  return [
    // 'prjo_dap' => [
    //   'render element' => 'children',
    // ],
    'portfolios' => [
      'variables' => [
        'url' => NULL,
      ],
    ],
    'scenarios' => [
      'variables' => [
        'url' => NULL,
      ],
    ],
    'evaluation_infograph' => [
      'variables' => [],
    ],
    'evaluation_pyplotly' => [
      'variables' => [],
    ],
    'evaluation_outline' => [
      'variables' => [],
    ],
    'comparison' => [
      'variables' => [],
    ],
    'afclm' => [
      'variables' => [],
    ]
  ];
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function prjo_dap_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'prjo_dap_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function prjo_dap_user_login_form_submit($form, FormStateInterface $form_state) {
  $url = Url::fromRoute('prjo_dap.portfolios');
  $form_state->setRedirectUrl($url);
}
