<?php

/**
 * @file
 * Contains prjo_dap.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function prjo_dap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the prjo_dap module.
    case 'help.page.prjo_dap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function prjo_dap_theme() {
  return [
    // 'prjo_dap' => [
    //   'render element' => 'children',
    // ],
    'portfolios' => [
      'variables' => [
        'portfolios' => NULL,
      ],
    ],
    'evaluation_infograph' => [
      'variables' => [],
    ],
    'evaluation_pyplotly' => [
      'variables' => [],
    ],
    'evaluation_outline' => [
      'variables' => [],
    ]
  ];
}
